default-dispenser: true
default-note-block: false
default-workbench: true
default-door: true
default-lever: true
default-pressure-plate: true
default-button: true
default-jukebox: true
default-repeater: false
default-trap-door: true
default-fence-gate: true
default-brewing-stand: true
default-cauldron: true
default-enchantment-table: true
default-ender-chest: true
default-tripwire: true
default-beacon: true
default-anvil: true
default-comparator: false
default-hopper: true
default-dropper: true
default-daylight-detector: false
